"""The derivation mirrors stay level with the code that cites them. [infrastructure]

Not a thesis test: there is no mathematics here, and unlike the B1-B3 tests these pass
from day one. They catch two cheap ways for code and derivation to drift apart:

  1. somebody edits docs/derivations/*.md directly instead of editing the vault note
     (the mirrors are generated, so such an edit is lost on the next sync);
  2. a docstring cites a derivation tag that does not exist, e.g. a typo'd [A5 §1].

The half that needs the vault itself - "has the author changed A2 since we mirrored it?"
- cannot run here, because the dev container deliberately cannot see the Windows
filesystem. Run that in WSL:

    python3 scripts/sync_derivations.py --check --vault "<path to 2_2_Derivations>"
"""

from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path

import pytest

pytestmark = pytest.mark.docs

REPO_ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = REPO_ROOT / "docs" / "derivations" / "MANIFEST.json"
SYNC_SCRIPT = REPO_ROOT / "scripts" / "sync_derivations.py"


def _load_sync_module():
    """Import scripts/sync_derivations.py by path (scripts/ is not a package)."""
    spec = importlib.util.spec_from_file_location("sync_derivations", SYNC_SCRIPT)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def manifest() -> dict:
    assert MANIFEST_PATH.exists(), "run scripts/sync_derivations.py --update --vault <path>"
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def test_every_mirror_matches_the_manifest(manifest: dict) -> None:
    """A mirror whose hash moved was hand-edited. Edit the vault note and re-sync instead."""
    for entry in manifest["derivations"]:
        path = REPO_ROOT / entry["file"]
        assert path.exists(), f"missing mirror {entry['file']}"
        digest = hashlib.sha256(path.read_text(encoding="utf-8").encode("utf-8")).hexdigest()
        assert digest == entry["mirror_sha256"], (
            f"{entry['file']} was edited by hand. Mirrors are generated: change the vault "
            f"note {entry['source_name']} and re-run scripts/sync_derivations.py --update."
        )


def test_every_citation_tag_in_code_resolves(manifest: dict) -> None:
    """Every [A<n> §<s>] tag in crop_mot/ names a derivation that is actually mirrored."""
    sync = _load_sync_module()
    known = {entry["tag"] for entry in manifest["derivations"]}
    cited = sync.citations_in_code()
    unknown = {tag: files for tag, files in cited.items() if tag not in known}
    assert not unknown, f"citations to derivations that do not exist: {unknown}"


def test_mirrors_are_marked_do_not_edit(manifest: dict) -> None:
    """The header is what tells a reader (human or agent) which file is the source of truth."""
    for entry in manifest["derivations"]:
        head = (REPO_ROOT / entry["file"]).read_text(encoding="utf-8")[:400]
        assert "DO NOT EDIT THIS FILE" in head
        assert entry["source_name"] in head
