"""Keep docs/derivations/ level with the thesis vault notes.

Why this exists
    Code bodies cite the derivations by tag, e.g. "[A2 §2]". Those derivations live in
    the author's Obsidian vault on the Windows side, which the dev container cannot
    see. docs/derivations/ holds a converted MIRROR of each note so the code and its
    justification travel together, and this script is what keeps the mirror honest.

Two halves, because the vault is not reachable from everywhere:
    in the container   tests/test_derivations_in_sync.py checks the mirrors still match
                       MANIFEST.json and that every citation tag in the code resolves.
    in WSL (not the    this script, with --vault, compares the mirrors against the real
    container)         vault notes and reports which derivations have drifted, together
                       with the code that cites them and therefore needs re-reading.

Usage (run from the repo root, inside WSL where /mnt/c is visible):

    python3 scripts/sync_derivations.py --check \
        --vault "/mnt/c/Users/<you>/OneDrive/.../Thesis/2_Project/2_2_Derivations"

    python3 scripts/sync_derivations.py --update --vault "<same path>"

    python3 scripts/sync_derivations.py --check          # mirror-only check, no vault

Standard library only. Nothing here is thesis mathematics; it is bookkeeping.
"""

from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MIRROR_DIR = REPO_ROOT / "docs" / "derivations"
MANIFEST_PATH = MIRROR_DIR / "MANIFEST.json"
CODE_DIR = REPO_ROOT / "crop_mot"

# Which vault notes are mirrored, and under which id the code cites them.
# A4-A6 are placeholders in the vault and are deliberately not mirrored.
SOURCES = {
    "A0": ("A0 Measurement modelling and handeling Clutter.md", "Measurement modelling and handling clutter"),
    "A1": ("A1 Bayes to Kalman Derivation.md", "Bayes to Kalman derivation"),
    "A2": ("A2 Bernoulli existence update.md", "Bernoulli existence update"),
    "A3": ("A3 Normalization and Pruning across competing global Hypotheses.md", "Normalisation and pruning across competing global hypotheses"),
}

# A citation tag as it appears in code: [A2], [A2 §2], [A2 §2.1].
CITATION_RE = re.compile(r"\[(A[0-9])(\s*§[^\]]*)?\]")

_FRONTMATTER_RE = re.compile(r"\A---\r?\n.*?\r?\n---\r?\n", re.DOTALL)
_EMBED_RE = re.compile(r"!\[\[([^\]]+)\]\]")
_IMAGE_RE = re.compile(r"!\[[^\]]*\]\(([^)]+)\)")
_WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_lf(path: Path, text: str) -> None:
    """Write UTF-8 with LF endings on any host (Path.write_text(newline=) is 3.10+)."""
    with open(str(path), "w", encoding="utf-8", newline="\n") as handle:
        handle.write(text)


def _flatten_wikilink(match: re.Match) -> str:
    inner = match.group(1)
    if "|" in inner:
        return inner.split("|", 1)[1]
    return inner.replace("#", " - ")


def convert(raw: str, tag: str, title: str, source_name: str, source_sha: str, when: str) -> str:
    """Turn one Obsidian note into a mirror a text-only reader can use.

    Frontmatter is dropped, [[wikilinks]] are flattened to their display text, and image
    embeds become visible placeholders so a missing figure is obvious rather than silent.
    LaTeX, callouts, tables and mermaid blocks are left exactly as written: the whole
    point is that the expression in the mirror is character-for-character the one in the
    thesis.
    """
    body = _FRONTMATTER_RE.sub("", raw)
    body = _EMBED_RE.sub(lambda m: "> **[figure omitted in mirror: %s - see the vault note]**" % m.group(1), body)
    body = _IMAGE_RE.sub(lambda m: "> **[figure omitted in mirror: %s - see the vault note]**" % m.group(1), body)
    body = _WIKILINK_RE.sub(_flatten_wikilink, body)
    body = body.replace("\r\n", "\n").strip()

    header = (
        "<!--\n"
        "MIRROR OF A THESIS VAULT NOTE - DO NOT EDIT THIS FILE.\n"
        "Source of truth: %s (Obsidian vault, 2_Project/2_2_Derivations/).\n"
        "Edit there, then re-run scripts/sync_derivations.py --update --vault <path>.\n"
        "-->\n\n"
        "# %s - %s\n\n"
        "Mirror copied %s from `%s` (source sha256 `%s`).\n"
        "Cite this note in code as `[%s §<section>]`.\n"
        "**If the code and this file disagree, the vault note wins: stop and ask the author.**\n\n"
        "---\n\n"
    ) % (source_name, tag, title, when, source_name, source_sha[:12], tag)
    return header + body + "\n"


def load_manifest() -> dict:
    if not MANIFEST_PATH.exists():
        return {"derivations": []}
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def citations_in_code() -> dict:
    """tag -> sorted list of repo-relative files whose text cites it."""
    found = {}
    for path in sorted(CODE_DIR.rglob("*.py")):
        text = path.read_text(encoding="utf-8")
        for match in CITATION_RE.finditer(text):
            tag = match.group(1)
            rel = str(path.relative_to(REPO_ROOT))
            found.setdefault(tag, set()).add(rel)
    return {tag: sorted(files) for tag, files in found.items()}


def cmd_update(vault: Path) -> int:
    MIRROR_DIR.mkdir(parents=True, exist_ok=True)
    when = datetime.date.today().isoformat()
    entries = []
    for tag, (source_name, title) in sorted(SOURCES.items()):
        source_path = vault / source_name
        if not source_path.exists():
            print("MISSING in vault: %s" % source_path)
            return 2
        raw = source_path.read_text(encoding="utf-8")
        source_sha = sha256_text(raw)
        mirror_text = convert(raw, tag, title, source_name, source_sha, when)
        mirror_path = MIRROR_DIR / ("%s.md" % tag)
        write_lf(mirror_path, mirror_text)
        entries.append(
            {
                "tag": tag,
                "title": title,
                "file": "docs/derivations/%s.md" % tag,
                "source_name": source_name,
                "source_sha256": source_sha,
                "mirror_sha256": sha256_text(mirror_text),
                "copied_at": when,
            }
        )
        print("wrote %s  (%s)" % (mirror_path.relative_to(REPO_ROOT), title))
    write_lf(
        MANIFEST_PATH,
        json.dumps({"generated_by": "scripts/sync_derivations.py", "derivations": entries}, indent=2) + "\n",
    )
    print("wrote %s" % MANIFEST_PATH.relative_to(REPO_ROOT))
    return 0


def cmd_check(vault: Path = None) -> int:
    """Report drift. Exit code 0 = level, 1 = drift found, 2 = broken setup."""
    manifest = load_manifest()
    entries = manifest.get("derivations", [])
    if not entries:
        print("No manifest yet: run with --update --vault <path>.")
        return 2

    cites = citations_in_code()
    drift = 0

    for entry in entries:
        mirror_path = REPO_ROOT / entry["file"]
        if not mirror_path.exists():
            print("MISSING mirror: %s" % entry["file"])
            drift += 1
            continue
        mirror_sha = sha256_text(mirror_path.read_text(encoding="utf-8"))
        if mirror_sha != entry["mirror_sha256"]:
            print("EDITED mirror (mirrors are read-only): %s" % entry["file"])
            drift += 1
        if vault is not None:
            source_path = vault / entry["source_name"]
            if not source_path.exists():
                print("MISSING in vault: %s" % source_path)
                drift += 1
                continue
            if sha256_text(source_path.read_text(encoding="utf-8")) != entry["source_sha256"]:
                users = cites.get(entry["tag"], [])
                print("DRIFTED: %s changed in the vault since it was mirrored." % entry["tag"])
                print("         re-read these, they cite it: %s" % (", ".join(users) if users else "(nothing yet)"))
                drift += 1

    unknown = sorted(set(cites) - {e["tag"] for e in entries})
    if unknown:
        print("UNKNOWN citation tags in code (no such derivation): %s" % ", ".join(unknown))
        drift += len(unknown)

    if drift == 0:
        print("derivations and code are level (%d mirrors, %d cited)" % (len(entries), len(cites)))
        return 0
    print("\n%d problem(s). After re-reading the code above, re-run with --update." % drift)
    return 1


def main(argv: list = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--vault", type=Path, default=None, help="path to the vault's 2_2_Derivations folder")
    parser.add_argument("--update", action="store_true", help="re-copy the mirrors and rewrite MANIFEST.json")
    parser.add_argument("--check", action="store_true", help="report drift (default)")
    args = parser.parse_args(argv)

    if args.update:
        if args.vault is None:
            print("--update needs --vault")
            return 2
        return cmd_update(args.vault)
    return cmd_check(args.vault)


if __name__ == "__main__":
    sys.exit(main())
